using System.ComponentModel.DataAnnotations;

namespace Pulse.Library.Core.Schema;


/// Definition of an ENTITY TYPE(defined in init.json) in the AODB.
public abstract class EntityType
{
    /// Internal name used as a unique identifier for the entity type.
    /// This constraint is due to internal limitations in naming Postgresql tables 
    [MaxLength(56)]
    [RegularExpression(@"^[a-z_]{0,56}$")]
    public string InternalName { get; set; } = null!;

    /// Name of the entity type as displayed in a user interface.
    public string DisplayName { get; set; } = null!;
    
    /// Description of the entity type.
    public string? Description { get; set; }

    /// Status of the entity.
    public Status Status { get; set; }
    
    /// A list of indexes, which are used for querying the EntityType
    public IEnumerable<Index> Indexes { get; set; } = new List<Index>();
    
    /// A RootEntityType can have a number of Unique Constraints,
    /// which each determine that certain attributes (or expressions on attributes) must be unique
    public IEnumerable<UniqueConstraint> UniqueConstraints { get; set; } = new List<UniqueConstraint>();
    
    /// Definitions of the value attribute types in this entity type.
    public virtual IEnumerable<AttributeType> AttributeTypes { get; set; } = new List<AttributeType>();

    
    /// Definitions of the complex attribute types in this entity type.
    public virtual IEnumerable<ComplexAttributeType> ComplexAttributeTypes { get; set; } = new List<ComplexAttributeType>();
    
    /// Definitions of the actions in this entity type.
    public virtual IEnumerable<Action> Actions { get; set; } = new List<Action>();

    /// Autogenerated IEqualityComparer - to be added if needed.
}